version: "3.9"

services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user_service:
    build:
      context: .              # Adjust if Dockerfile is inside ./user_service
      dockerfile: Dockerfile  # Explicit if needed
    container_name: user_service
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
