# Generated by Django 5.2 on 2025-05-02 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.CharField(max_length=64)),
                ('location_y', models.CharField(max_length=64)),
                ('warehouse_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_restocked', models.DateTimeField(blank=True, null=True)),
                ('minimum_stock_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'warehouse_inventory',
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouseinventory')),
            ],
            options={
                'db_table': 'inventory_transactions',
            },
        ),
        migrations.AddConstraint(
            model_name='warehouseinventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='positive_quantity'),
        ),
    ]
