# Generated by Django 5.2 on 2025-05-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_warehouse_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseinventory',
            name='supplier_id',
        ),
        migrations.CreateModel(
            name='WarehouseSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse')),
            ],
            options={
                'db_table': 'warehouse_supplier',
                'unique_together': {('warehouse', 'supplier_id')},
            },
        ),
    ]
