version: '3.9'

services:
  django-app:
    build: .
    container_name: django_app
    ports:
      - "${PORT:-8000}:8000"
    env_file:
      - ./warehouse_managment/warehouse_managment/.env
    volumes:
      - .:/app
    working_dir: /app/warehouse_managment
    restart: unless-stopped
