services:
  # database:
  #   image: 'postgres:latest'
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #   networks:
  #     - postgres-network
  #   volumes:
  #     - ${PWD}/db-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/

  psql-client:
    image: postgres:latest
    entrypoint: ["bash"]
    tty: true
    stdin_open: true
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge