# Generated by Django 5.2 on 2025-05-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_SKU',
            field=models.CharField(default='SKU000', max_length=30, unique=True),
        ),
    ]
