name: Django Forecasting CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DJANGO_DEBUG: True
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Tests
      working-directory: ./warehouse_managment
      run: |
      
         python manage.py test --keepdb
